// Custom Events
export const CHANGE_COLOR = 'CHANGE_COLOR';

// localStorage
export const STORAGE_MATRIX_SIZE = 'STORAGE_MATRIX_SIZE';
export const STORAGE_CANVAS_IMAGE = 'STORAGE_CANVAS_IMAGE';
export const STORAGE_PREV_COLOR = 'STORAGE_PREV_COLOR';
export const STORAGE_CURRENT_COLOR = 'STORAGE_CURRENT_COLOR';
export const STORAGE_CURRENT_TOOL = 'STORAGE_CURRENT_TOOL';
